### ISSUE TITLE
Default to four words with no padded digits?

### ISSUE THREAD

**Issue by hugovk** [adambirds/xkcd-password-gen#1]
Nice generator!

Is the idea of [xkcd 939](https://xkcd.com/936/) to use words and avoid numbers?

![](https://imgs.xkcd.com/comics/password_strength.png)

So should the defaults be the same as `-n 4 --no-padding-digits`?

```console
$ xkcd-pass
PrudeMummifiedSuing11
$ xkcd-pass -n 4 --no-padding-digits
TwisterSynopsisStylizedOutthink
```

(And maybe even default to all lower case?)

---

Also `--min MIN_LENGTH` ("Generate passphrases containing at least MIN_LENGTH words") doesn't appear to work, unless I'm misunderstanding something:

```console
$ xkcd-pass --min 4 --no-padding-digits
CertaintyOperationRemorse
```

Thanks!

**Comment by adambirds** [comment]
Thanks for the input @hugovk

I'm certainly happy to set the default of 4 words, but I would like to keep digits as default. The main reason being whilst this is inspired by [XKCD 936](https://xkcd.com/936/), its not an exact remake and the inclusion of numbers and the capitals increases the bits of entropy of the password considerably and makes it more compatible with most services out there that require at least 1 lowercase, uppercase and digit in the password. Setting the default to lowercase and no numbers would reduce its easiness of use with most services.

With regards to the `--min`, the default wordfile used only includes words between 5 and 9 characters. So setting the `--min` of 4 will include the entire wordlist. Setting the `--min` to 7, would only includes words of 7,8, and 9 characters. The same also counts for `--max`, setting it to 10 would also include the entire wordlist. I think this is explained in `README.md` but I think this is reasonable to add into `xkcd-pass --help` at least to explain for the default wordfile `eff-long`.

**Comment by hugovk** [comment]
Okay, thanks for the explanation.

I completely misunderstood `--min` and `--max` and thought they applied to the number of words, not the character length of individual words.

Perhaps something like this is clearer?

```diff
-Generate passphrases containing at least MIN_LENGTH words.
+Generate passphrases containing words of at least MIN_LENGTH characters.
```

**Comment by adambirds** [comment]
Yes, that's certainly an improvement, do you want to submit a PR for it? If not happy to do it myself.

**Comment by adambirds** [comment]
I've made these changes, these will be pushed as `1.0.8` in the next day or two. Thanks @hugovk

**Comment by adambirds** [comment]
@hugovk `1.0.9` is out now. Had issues with `1.0.8`. You can update with `pip install xkcd-pass -U`

**Comment by hugovk** [comment]
Thanks!
